package com.lithial.me.aencEx;

import java.io.File;
import java.util.Arrays;
import java.util.logging.Logger;

import net.minecraftforge.common.config.Configuration;

import com.lithial.me.aencEx.api.IdExtension;

import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = "AencEx", name = "AencEx", version = "0.0.1",dependencies = "")
 
public class AencEx {
	@Mod.Instance("AencEx")
	public static AencEx instance;
	//@SidedProxy(clientSide = "me.core.moreEnchantments.Core.ClientProxy", serverSide = "me.core.moreEnchantments.Core.CommonProxy")
	 
	Configuration config;
	
	public File modDir;
	public static Logger log;

	public AencEx() {
	}

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		IdExtension.expand();
		getModMeta(event.getModMetadata());
	 
 

	}

	@EventHandler
	public void Initiate(FMLInitializationEvent Event) {
		FMLLog.fine("AencEx >> Saving Configuration After Init", new Object[0]);
 }

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
 
	}

	private void getModMeta(ModMetadata meta) {

		meta.authorList = Arrays.asList(new String[] { "Lithial, DarkHax, Freyja" });
		meta.logoFile = "";
		meta.autogenerated = false;
		meta.credits = "Lithial";
		meta.description = "IdExtender. An essential part of more enchantments. Allows for more enchantment ids for almost any mod.";
		//meta.url = "http://www.minecraftforum.net/topic/1960242-more-enchantments-version-01-forgeupdatesmp-compatible/#entry24134479";
	}

}
